version: '3.8'

# When accessing elasticsearch from devcontainer, execute the following command.
# $ poetry run evtx2es --host host.docker.internal /path/to/eventlog.evtx

services:
  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: evtx2es-elasticsearch
    ports:
        - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:8.4.3
    container_name: evtx2es-kibana
    ports:
        - 5601:5601
    environment:
      - elasticsearch.host="http://localhost:9200"
